Extend python SDK with dataset environment parameter
marketredesign/pricecypher_python_sdk pull request #33
Opened 2024-04-24 15:00 UTC by levykort1

## Proposed changes

Extend python SDK with dataset env parameter.

## Types of changes

What types of changes does your code introduce to this repository?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
Explain here how to run your unit tests, and explain how to execute manual testing. 

### Unit testing

NA

### Manual testing

NA

## Further comments

@marijnvanderhorst  not sure if it is simple as this?

2024-04-24 16:37 UTC, marijnvanderhorst requested changes
Let's avoid introducing a breaking change for this. Please see comments below.

2024-04-24 16:37 UTC, marijnvanderhorst commented on src/pricecypher/datasets.py
> +        dataset_environment,
Please note that this `get_transactions` function is currently being used in numerous places. Adding an additional parameter somewhere in-between existing parameters, would mean that all usages of this function across all scripts need to be updated to pass a value for this new `environment` parameter. __I.e., changing the signature of this function as proposed in this PR, would be considered a "breaking change".__

Please observe that such a breaking change can very easily be avoided by placing this new parameter all the way at the _end_. Since the function definition already includes other parameters at the end with a default value set, we must then also specify a default value for the new `dataset_environment` parameter (`None` in this case).

We should then make sure that the new parameter behaves in such a way that no existing functionality is altered in any way, _unless_ an environment key is given. I.e., I'd suggest including the given `environment` key in the `request_data` if, and only if, the given value is `not None`.

2024-04-24 16:37 UTC, marijnvanderhorst commented on src/pricecypher/datasets.py
> +            'dataset_environment': dataset_environment,
```suggestion
            'environment': dataset_environment,
```
The key in the request data must be exactly `environment` since that it what the Dataset Service will try to lookup in the request data. I'd suggest conditionally including this value though (see first comment).

2024-04-24 16:37 UTC, marijnvanderhorst commented on src/pricecypher/datasets.py
> +        :param param dataset_environment: Dataset environment to retrieve transactions for.
```suggestion
        :param param dataset_environment: Key specifying the "environment" of the underlying data intake to query. 
            Use `None` (the default) to query transactions from the latest intake, regardless of the associated 
            environment with that intake.
```

2024-04-25 07:01 UTC, levykort1 commented on src/pricecypher/datasets.py
> +        dataset_environment,
Thanks for this clear explanation, should be updated now in the commit  [#5738c55](https://github.com/marketredesign/pricecypher_python_sdk/pull/33/commits/5738c5505552a7cfb8419de15b1eebcce9aa52f3)

2024-04-25 10:20 UTC, marijnvanderhorst approved these changes
Thanks for the changes!

Tested locally and seems to be working as intended now 👍

2024-04-25 10:21 UTC, merged